#!/bin/bash

# ----------------------------------------------------------------------------

alias l="/bin/ls  -slFGh"
alias la="/bin/ls -saFGh"
alias ll="/bin/ls -slaFGh"

alias grep="grep --color=auto"

alias ..="cd .."

which bat  >/dev/null && alias cat="bat"
which tree >/dev/null && alias tree="tree -C" && alias t="tree"

# ----------------------------------------------------------------------------

mcd(){
  /bin/mkdir -p "${*}" && cd "${1}"
}

alias mkdir="/bin/mkdir -p"

# -----------------------------------------------------------------------------

alias e='${EDITOR:-vim}'

brave(){
  open "https://search.brave.com/search?q=${*// /+}"
}

google(){
  open "https://search.google.com/search?q=${*// /+}"
}

# GIT -------------------------------------------------------------------------

alias gss='git status >/dev/null && $EDITOR -c "Git | bd 1"'
alias gs="git status --short"
alias gl="git log --oneline --graph"
alias gb="git branch -a"
alias gch="git checkout"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gP="git pull"

# ----------------------------------------------------------------------------

which python3 >/dev/null && alias python="python3"

# SYSTEM ADMINISTRATION ------------------------------------------------------

alias su="/usr/bin/su -l"
alias reboot="sudo reboot"

# ----------------------------------------------------------------------------

wtfismyip() {
  curl "https://www.wtfismyip/${1:-json}"
}

# ----------------------------------------------------------------------------
