#!/usr/bin/env bash
# shellcheck disable=SC2164

# ----------------------------------------------------------------------------

alias l="/bin/ls  -slFGh"
alias la="/bin/ls -saFGh"
alias ll="/bin/ls -slaFGh"

alias grep="grep --color=auto"

alias ..="cd .."

which bat  >/dev/null && alias cat="bat"
which tree >/dev/null && alias tree="tree -C" && alias t="tree"

# ----------------------------------------------------------------------------

alias cfg='cd $HOME/.config'

# ----------------------------------------------------------------------------

alias mkdir="/bin/mkdir -p"

mcd(){
  /bin/mkdir -p "$@" && cd "$1"
}

# -----------------------------------------------------------------------------

alias e='${EDITOR:-vim}'

if [ "$(uname)" = "Darwin" ]; then
  FIREFOX="/Applications/Firefox.app/Contents/MacOS/firefox-bin"
  [ -x "$HOME/$FIREFOX" ] && FIREFOX="$HOME/$FIREFOX"
  [ -x "$FIREFOX" ] && alias firefox="$FIREFOX"
  unset FIREFOX
fi

google(){
  open "https://search.brave.com/search?q=${*// /+}"
}

# GIT -------------------------------------------------------------------------

alias gss='git status >/dev/null && $EDITOR -c "Git | bd 1"'
alias gs="git status --short"
alias gl="git log --oneline --graph"
alias gb="git branch -a"
alias gch="git checkout"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gP="git pull"

# ----------------------------------------------------------------------------

which python3 >/dev/null && alias python="python3"

# SYSTEM ADMINISTRATION ------------------------------------------------------

alias su="/usr/bin/su -l"

which reboot >/dev/null && alias reboot="sudo reboot"

if [ "$(uname)" = "Linux" ]; then
  if which apt >/dev/null; then
    alias apt="apt -y"
    alias apt-get="apt-get -y"
  fi
fi

# ----------------------------------------------------------------------------

alias wtfismyip="curl https://www.wtfismyip.com/json"

# ----------------------------------------------------------------------------
