#!/usr/bin/env bash

# ----------------------------------------------------------------------------

alias l='/bin/ls  -lFGh'
alias l='/bin/ls  -lFGh'
alias la='/bin/ls -aFGh'
alias ll='/bin/ls -laFGh'

which bat  >/dev/null && alias cat='bat'
which tree >/dev/null && alias tree='tree -C' && alias t='tree'

# ----------------------------------------------------------------------------

alias ..='cd ..'

cfg(){
  local CFG_HOME="$HOME/.dotfiles/main"
  [ -d "$CFG_HOME" ] || local CFG_HOME="$HOME/.config"
  [ -d "$CFG_HOME" ] && cd "$CFG_HOME" || return 1
}

# ----------------------------------------------------------------------------

alias mkdir='/bin/mkdir -p'

mcd(){
  mkdir "$1" && cd "$1" || return 1
}

which compdef >/dev/null && compdef -d mcd

chx(){
  if [ -x "$1" ]; then chmod -x "$1"; else chmod +x "$1"; fi
}

# TEXT EDITOR -----------------------------------------------------------------

alias e='${EDITOR:-vim}'

# GIT -------------------------------------------------------------------------

alias gss='git status >/dev/null && $EDITOR -c "Git | bd 1"'
alias gs="git status --short"
alias gl="git log --oneline --graph"
alias gb="git branch -a"
alias gch="git checkout"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gP="git pull"

#------------------------------------------------------------------------------

which python3 >/dev/null && alias python='python3' && alias py='python'

#------------------------------------------------------------------------------

alias su="/usr/bin/su -l"

sudo_aliases=(
  'reboot'
)

if [ "$(uname)" = "Darwin" ]; then
  sudo_aliases+=(
    'sysadminctl'
    'launchctl'
    'diskutil'
  )
fi

if [ "$(uname)" = "Linux" ]; then
  alias apt='apt -y'
  alias apt-get='apt-get -y'

  sudo_aliases+=(
    'apt'
    'apt-get'
  )
fi

if [ ! "$(whoami)" = "root" ]; then
  for sudo_alias in "${sudo_aliases[@]}"; do
    value="$(alias "$sudo_alias" 2>/dev/null | sed -E "s#.*'(sudo)* *(.*)'#\2#")"
    value="${value:-$(which "$sudo_alias" 2>/dev/null)}"
    [ -n "$value" ] && alias '$sudo_alias'='sudo $value'
  done
fi

unset sudo_aliases
unset sudo_alias
unset value

# ----------------------------------------------------------------------------
