#!/usr/bin/env bash
# shellcheck disable=SC2164

# ----------------------------------------------------------------------------

alias l="/bin/ls  -lFGh"
alias la="/bin/ls -aFGh"
alias ll="/bin/ls -laFGh"

alias grep="grep --color=auto"

alias ..="cd .."

which bat  >/dev/null && alias bat="bat --color=auto" && alias cat="bat"
which tree >/dev/null && alias tree="tree -C" && alias t="tree"

# ----------------------------------------------------------------------------

cfg(){
  cd "$HOME/dotfiles/$1" 2>/dev/null || cd "$HOME/.config/$1"
}

# ----------------------------------------------------------------------------

alias mkdir="/bin/mkdir -p"

mcd(){
  /bin/mkdir -p "${@[@]}" && cd "${@[1]}"
}

chx(){
  echo "${@[@]}" | xargs -n1 -P$# -I{} \
    bash -c '[ -f {} ] && ([ -x {} ] && chmod -x {} || chmod +x {}) || return'
}

# -----------------------------------------------------------------------------

alias e='${EDITOR:-vim}'

# GIT -------------------------------------------------------------------------

alias gss='git status >/dev/null && $EDITOR -c "Git | bd 1"'
alias gs="git status --short"
alias gl="git log --oneline --graph"
alias gb="git branch -a"
alias gch="git checkout"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gP="git pull"

# ----------------------------------------------------------------------------

which python3 >/dev/null && alias python="python3"

# SYSTEM ADMINISTRATION ------------------------------------------------------

alias su="/usr/bin/su -l"

which reboot >/dev/null && alias reboot="sudo reboot"

if [ "$(uname)" = "Linux" ]; then
  if which apt >/dev/null; then
    alias apt="apt -y"
    alias apt-get="apt-get -y"
  fi
fi

# ----------------------------------------------------------------------------
