#!/usr/bin/env bash

[ -f $HOME/.shrc ] && . $HOME/.shrc

# SHELL OPTS -----------------------------------------------------------------

# MISC
shopt -u mailwarn
shopt -s checkwinsize

# $PATH BEHAVIOR
# shopt sourcepath

# SPELLING CORRECTION
shopt -s dirspell # attempts to infer misspelled dir on `word-expansion`
shopt -s cdspell # attempts to infer misspelled dir for `cd`

# COMPLETION\EXPANSION
shopt -s hostcomplete

# GLOBBING
shopt -s dotglob
shopt -s nullglob
# shopt globskipdots
shopt -s nocaseglob
shopt -s nocasematch
shopt -s extglob

# HISTORY
shopt -s histverify
shopt -s cmdhist    # save multi-line commands as a single history entry
shopt -s histappend # save multi-line commands as a single history entry
# shopt lithist

if [ $((BASH_VERSINFO < 3)) = 1 ]; then
  shopt -s globstar # `**` performs recursive dir searches on filename expansion
  shopt -s autocd
  shopt -s progcomp_alias
fi

# READLINE -------------------------------------------------------------------

bind 'set mark-symlinked-directories on'
bind 'set colored-completion-prefix on'
bind 'set match-hidden-files on'

bind 'set visible-stats on'
bind 'set colored-stats on'

bind 'set history-preserve-point on'

# COMPLETION -----------------------------------------------------------------
bind 'set skip-completed-text on'
bind 'set show-all-if-ambiguous on'
bind 'set show-all-if-unmodified on'
bind 'set completion-ignore-case on'

# KEYBINDS -------------------------------------------------------------------

bind '"\C-k": history-substring-search-backward'
bind '"\C-j": history-substring-search-forward'

bind '"\t": menu-complete'            #\t => Tab
bind '"\e[Z": menu-complete-backward' #\t => Shift+Tab
