#!/usr/bin/env bash

[ -r ~/.shrc ] && . ~/.shrc

# SHELL OPTS -----------------------------------------------------------------

export BASH_SILENCE_DEPRECATION_WARNING=1
export MAILCHECK=0

shopt -s cmdhist
shopt -s histappend
shopt -s histverify
shopt -s checkwinsize
shopt -s dotglob
shopt -s extglob
shopt -s nocaseglob
shopt -s nocasematch
shopt -s nullglob
shopt -s hostcomplete
shopt -s autocd
shopt -s progcomp_alias

# READLINE -------------------------------------------------------------------

# bind 'set editing-mode vi'

bind 'set mark-symlinked-directories on'
bind 'set colored-completion-prefix on'
bind 'set match-hidden-files on'

bind 'set visible-stats on'
bind 'set colored-stats on'

bind 'set history-preserve-point on'

# COMPLETION -----------------------------------------------------------------
bind 'set skip-completed-text on'
bind 'set show-all-if-ambiguous on'
bind 'set show-all-if-unmodified on'
bind 'set completion-ignore-case on'

# KEYBINDS -------------------------------------------------------------------

bind '"\C-l": clear-screen'

bind '"\C-k": history-substring-search-backward'
bind '"\C-j": history-substring-search-forward'

bind '"\t": menu-complete'            #\t => <Tab>
bind '"\e[Z": menu-complete-backward' #\t => <S-Tab>
