#!/usr/bin/env bash
# shellcheck disable=SC1090 # disables shellcheck warning for "undefined" `~`

# RC\SOURCE FILES ------------------------------------------------------------

[ -r ~/.env ]     && . ~/.env
[ -r ~/.aliases ] && . ~/.aliases

# ----------------------------------------------------------------------------

CURRENT_SHELL=$(ps -p $$ -oargs= | sed -E "s#.*[-/]##")

# HISTORY MANAGEMENT ---------------------------------------------------------

export HISTCONTROL=ignoredups:erasedups
export HISTSIZE=1000
# export HISTTIMEFORMAT=""

mkdir -p ~/.cache/"$CURRENT_SHELL"
export HISTFILE=~/.cache/$CURRENT_SHELL/history

export LESSHISTFILE=/dev/null

# PROMPT ---------------------------------------------------------------------

# if ! which starship >/dev/null; then
#   sh <(curl -sSL https://starship.rs/install.sh 2>/dev/null) \
#         --force --bin-dir ~/.local/bin >/dev/null
# fi

which starship >/dev/null && eval "$(starship init "$CURRENT_SHELL")"

# ----------------------------------------------------------------------------

if which fzf >/dev/null; then
  if which fd >/dev/null; then
    export FZF_DEFAULT_COMMAND="fd --type f --hidden --exclude .git"
  else
    export FZF_DEFAULT_COMMAND="find . -type f 2> /dev/null"
  fi
  export FZF_DEFAULT_OPTS="--multi --cycle --reverse --border=rounded \
                            --preview='[ -f {} ] && cat {}'"
fi

# ----------------------------------------------------------------------------
