#!/usr/bin/env bash

# RC\SOURCE FILES -------------------------------------------------------------

[ -r ~/.env ]     && . ~/.env
[ -r ~/.aliases ] && . ~/.aliases

# ----------------------------------------------------------------------------

CURRENT_SHELL=$(ps -p $$ -oargs= | sed -E "s#.*[-/]##")

# HISTORY MANAGEMENT ----------------------------------------------------------

export HISTCONTROL=both
export HISTTIMEFORMAT=""
mkdir -p ~/.local/share/"$CURRENT_SHELL"
export HISTFILE=~/.local/share/"$CURRENT_SHELL"/"$CURRENT_SHELL"_history
export LESSHISTFILE=/dev/null

# PROMPT ---------------------------------------------------------------------

# if ! which starship >/dev/null; then
#   curl "https://starship.rs/install.sh" -sSO --create-dirs --output-dir "$HOME/.cache/starship" \
#     && sh $HOME/.cache/starship/install.sh --force --bin-dir $HOME/.local/bin >/dev/null
# fi

which starship >/dev/null && eval "$(starship init "$CURRENT_SHELL")"

#------------------------------------------------------------------------------

if which fzf >/dev/null; then
  if which fd >/dev/null; then
    export FZF_DEFAULT_COMMAND='fd --type f --hidden --exclude .git'
  else
    export FZF_DEFAULT_COMMAND='find . -type f 2> /dev/null'
  fi
  export FZF_DEFAULT_OPTS="--multi --cycle --reverse --border=rounded \
                            --preview='[ -f {} ] && cat {}'"
fi

#------------------------------------------------------------------------------

unset CURRENT_SHELL
