#!/bin/bash

# RC\SOURCE FILES ------------------------------------------------------------

# shellcheck disable=SC1091
[ -f "$HOME/.env" ]     && . "$HOME/.env"
[ -f "$HOME/.aliases" ] && . "$HOME/.aliases"

# ----------------------------------------------------------------------------

CURRENT_SHELL=$(ps -p $$ -oargs= | sed -E "s#.*[-/]##")

# HISTORY MANAGEMENT ---------------------------------------------------------

export HISTCONTROL=ignoredups:erasedups
export HISTSIZE=1000

mkdir -p "$HOME/.cache/$CURRENT_SHELL"
export HISTFILE="$HOME/.cache/$CURRENT_SHELL/history"

export LESSHISTFILE=/dev/null

# PROMPT ---------------------------------------------------------------------

if ! which starship >/dev/null; then
  sh <(curl -sSL https://starship.rs/install.sh) \
    --bin-dir "$HOME/.local/bin" --force >/dev/null  
fi

eval "$(starship init "$CURRENT_SHELL" 2>/dev/null)"

# ----------------------------------------------------------------------------

[ -f "$HOME/.config/fzf/fzf.sh" ] && . "$HOME/.config/fzf/fzf.sh"

# ----------------------------------------------------------------------------
