#!/usr/bin/env zsh

#-----------------------------------------------------------------------------

[ -f $HOME/.shrc ] && . $HOME/.shrc

#-----------------------------------------------------------------------------

plugins=(
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-syntax-highlighting
  hlissner/zsh-autopair
)

for plugin in $plugins; do
  PLUGIN_DIR=$HOME/.local/share/zsh/plugins/${plugin#*/}
  [ ! -d $PLUGIN_DIR ] && git clone --quiet https://github.com/$plugin $PLUGIN_DIR
  . $PLUGIN_DIR/zsh-*.plugin.zsh
done
unset plugins plugin PLUGIN_DIR 

#-----------------------------------------------------------------------------

completions=(
  zsh-users/zsh-completions
)

[ "$(uname)" = "Darwin" ] && completions+=(
  nilsonholger/osx-zsh-completions
)

for completion in $completions; do
  COMP_DIR=$HOME/.local/share/zsh/completions/${completion#*/}
  if [ ! -d $COMP_DIR ]; then
    git clone --quiet https://github.com/$completion $COMP_DIR
    rsync -aL $HOME/.local/share/zsh/completion/**/_* ${COMP_DIR%/*}/
  fi
done
unset completions completion COMP_DIR

which brew >/dev/null && FPATH="$(brew --prefix)/share/zsh/site-functions:$FPATH"
FPATH="$HOME/.local/share/zsh/site-functions:$FPATH"

autoload -Uz compinit && compinit -d "$HOME/.cache/zsh/compdump"

which mcd 2>&1 >/dev/null && compdef -d mcd

#-----------------------------------------------------------------------------

setopt auto_cd
setopt cd_silent
setopt chase_links   # go to actual symlink dir rather in cd

setopt null_glob
# setopt dot_glob
setopt extended_glob
setopt no_case_glob
# setopt glob_complete
setopt complete_in_word

setopt no_auto_remove_slash

setopt menu_complete # tab completion on first tab hit

setopt extended_history
setopt share_history
setopt hist_verify
setopt hist_append
setopt inc_append_history
setopt hist_ignore_space
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_expire_dups_first
setopt hist_find_no_dups

setopt nobeep

#-----------------------------------------------------------------------------

bindkey "^H" vi-cmd-mode

bindkey "^[[Z" .reverse-menu-complete # Shift+Tab

bindkey "^[[A" up-line-or-search   # up arrow
bindkey "^[[B" down-line-or-search # down arrow

bindkey "^O" autosuggest-accept

bindkey "^K" up-line-or-search
bindkey "^J" down-line-or-search
