#!/usr/bin/env zsh

#-----------------------------------------------------------------------------

[ -r $HOME/.shrc ] && . $HOME/.shrc

#-----------------------------------------------------------------------------

plugins=(
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-syntax-highlighting
  hlissner/zsh-autopair
)

for plugin in $plugins; do
  PLUGIN_DIR=$HOME/.local/share/zsh/plugins/${plugin#*/}
  [ ! -d $PLUGIN_DIR ] && git clone --quiet https://github.com/$plugin $PLUGIN_DIR
  . $PLUGIN_DIR/zsh-*.plugin.zsh
done
unset plugins plugin PLUGIN_DIR 

#-----------------------------------------------------------------------------

completions=(
  zsh-users/zsh-completions
)

[ "$(uname)" = "Darwin" ] && completions+=(
  nilsonholger/osx-zsh-completions
)

for completion in $completions; do
  COMP_DIR="$HOME/.local/share/zsh/plugins/${completion#*/}"
  [ ! -d "$COMP_DIR" ] && git clone -q https://github.com/$completion "$COMP_DIR"
  FPATH="$FPATH:$(dirname $COMP_DIR/**/_* | head -n1)"
done
unset completions completion COMP_DIR

which brew &>/dev/null && FPATH="$FPATH:$(brew --prefix)/share/zsh/site-functions"

FPATH="$HOME/.local/share/zsh/site-functions:${FPATH}"

zstyle ':completion::complete:*' cache-path "$HOME/.cache/zsh/zcompcache"

autoload -Uz compinit && compinit -d "$HOME/.cache/zsh/zcompdump"

compdef -P _cd -N mcd

#-----------------------------------------------------------------------------

setopt auto_cd
setopt cd_silent
setopt auto_pushd
setopt pushd_silent
setopt chase_links   # go to actual symlink dir rather in cd

setopt null_glob
# setopt dot_glob
setopt extended_glob
setopt no_case_glob
setopt no_case_match

setopt no_hash_all
setopt no_hash_list_all
setopt no_hash_dirs

setopt glob_complete
setopt complete_in_word
setopt menu_complete # tab completion on first tab hit
setopt no_auto_remove_slash

setopt extended_history

setopt share_history
setopt hist_append
setopt inc_append_history

setopt hist_verify
setopt hist_no_store 

setopt hist_ignore_space
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_expire_dups_first
setopt hist_find_no_dups

setopt nobeep
setopt interactive_comments

#-----------------------------------------------------------------------------

bindkey "^H" vi-cmd-mode

bindkey "^[[Z" .reverse-menu-complete # Shift+Tab

bindkey "^[[A" up-line-or-search   # up arrow
bindkey "^[[B" down-line-or-search # down arrow

bindkey "^O" autosuggest-accept

bindkey "^K" up-line-or-search
bindkey "^J" down-line-or-search
