#!/bin/bash
#------------------------------------------------------------------------------
#{ BUILTINS W\ PREFERRED DEFAULT ARGS }----------------------------------- {{{1

# --- SYS (CONFIGUR\ADMINSTR)ATION
alias sysctl="sudo sysctl"

# --- FORMAT OUTPUT
LS=$(command -v exa || command -v ls)
alias ls="$LS -FG"
alias la="$LS -AFG"
alias lA="$LS -AFGR"
alias cat='bat'
alias grep="grep --color=auto"

# -- ERROR HANDLED
alias mkdir='mkdir -p'
alias mkd='mkdir -p'
#}}}1
#{ CUSTOM COMMANDS }------------------------------------------------------ {{{1

function mcdir(){
    mkdir -p "${*}" && cd "${1}"
}
alias mcd='mcdir'

alias e="$(command -v nvim || command -v vim)"
#}}}1
# { GIT }----------------------------------------------------------------- {{{1

alias g="git"
# --- LISTING
alias gbr="git branch"
alias gl="git log"
alias gco="git checkout"
alias gs="git status"
# --- ADDING \ COMMITTING
alias ga="git add"
alias gcmt="git commit"
# --- UNDOING \ (RE)MOVINIG
alias grsv="git revert"
#}}}1
# { TMUX }---------------------------------------------------------------- {{{1

alias tm='tmux -u -f $HOME/.tmux.conf'
# --- [ LISTING ]
alias tmlw='tmux list-windows'
alias tmls='tmux list-sessions'
# --- [ ATTACHING \ DETTACHING ]
alias tma='tmux -u -f $TMUX_CONFIG_HOME attach'
alias tmd='tmux detach'
# --- [ CREATING \ ADDING CLIENTS ]
alias tmns='tmux -u -f $HOME/.tmux.conf new-session'
alias tmnw='tmux -u -f $TMUX_CONFIG_HOME new-window'
# --- [ KILLING \ REMOVING CLIENTS ]
alias tmks='tmux -u -f $HOME/.tmux.conf new-session'
alias tmkw='tmux -u -f $TMUX_CONFIG_HOME new-window'
#}}}1
#------------------------------------------------------------------------------
# vim: filetype=bash:foldmethod=marker:
