#!/usr/bin/env bash

alias ..="cd ..;"

alias l="/bin/ls -FGhlos"
alias ll="l -a"

alias grep="grep --color=auto"

alias e='${EDITOR:-vim}'

alias reboot="sudo reboot"

if which tree >/dev/null; then 
  alias tree="tree -C --gitignore"
  alias t="tree"
fi

alias dedup='awk "!x[\$0]++"'
