#!/usr/bin/env bash

# HOMEBREW_ROOT="${HOME}/.local"

[ "${CPUTYPE}" = "x86_64" ] && HOMEBREW_ROOT="${HOMEBREW_ROOT:-/usr/local}"
[ "${CPUTYPE}" = "arm64" ]  && HOMEBREW_ROOT="${HOMEBREW_ROOT:-/opt}"

export PATH="${HOMEBREW_ROOT}/homebrew/bin:${PATH}"

if ! eval "$("${HOMEBREW_ROOT}/homebrew/bin/brew" shellenv)" >/dev/null; then

  URL="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
  bash <(export NONINTERACTIVE=1; curl -fqsSL ${URL}) \
    && brew autoupdate start --immediate --upgrade --greedy --cleanup >/dev/null \
    && brew analytics off \
    && brew completions link >/dev/null

  # if [ ! -x "$HOME/.local/homebrew/bin/brew" ]; then
  #   git clone --quite https://github.com/homebrew "$HOME/.local/homebrew" \
  #     && brew autoupdate start --immediate --upgrade --greedy --cleanup >/dev/null \
  #     && brew analytics off \
  #     && brew completions link >/dev/null
  # fi

fi

export HOMEBREW_ANALYTICS=0
# export HOMEBREW_CACHE="$HOME/.cache/Homebrew"
export HOMEBREW_CASK_OPTS="--force --no-quarantine"
export HOMEBREW_EVAL_ALL=1
# export HOMEBREW_BUNDLE_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/homebrew/Brewfile"
# export HOMEBREW_TEMP=/tmp

if [ "${HOMEBREW_ROOT}" = "${HOME}/.local" ]; then
  export HOMEBREW_CASK_OPTS="\
          ${HOMEBREW_CASK_OPTS} \
          --appdir=${HOME}/Applications \
          --font-dir=${HOME}/Library/Fonts"
fi

#------------------------------------------------------------------------------
