#!/usr/bin/env bash

[ "${CPUTYPE}" = "x86_64" ] && HOMEBREW_ROOT="${HOMEBREW_ROOT:-/usr/local}"
[ "${CPUTYPE}" = "arm64" ]  && HOMEBREW_ROOT="${HOMEBREW_ROOT:-/opt}"
[ "$(uname)"   = "Linux" ]  && HOMEBREW_ROOT="/home/linuxbrew/.linuxbrew"

eval "$("${HOMEBREW_ROOT}/homebrew/bin/brew" shellenv)"

if ! which brew >/dev/null; then

# TODO: Get user privledges and setup install path\method.

  URL="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
  bash <(export NONINTERACTIVE=1; curl -fqsSL "${URL}")

  # git clone --quite https://github.com/homebrew "${HOMEBREW_ROOT}/homebrew"

  brew autoupdate start --immediate --upgrade --greedy --cleanup >/dev/null
  brew completions link >/dev/null
fi

if [ "${HOMEBREW_ROOT}" = "${HOME}/.local" ]; then
  HOMEBREW_CASK_OPTS=(
    "--font-dir=${HOME}/Library/Fonts" 
    "--appdir${HOME}/Applications"
  )
fi

export HOMEBREW_CASK_OPTS=("--force --no-quarantine" "${HOMEBREW_CASK_OPTS[@]}")
export HOMEBREW_ANALYTICS=0
export HOMEBREW_EVAL_ALL=1
