#!/usr/bin/env bash

#-----------------------------------------------------------------------------

PATH="${HOME}/.local/sbin:${HOME}/.local/bin:${PATH}"

#-----------------------------------------------------------------------------

export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

#-----------------------------------------------------------------------------

case "$(uname)" in
  Darwin)
    [ -f "${HOME}/.config/sh/darwinrc" ] && . "$HOME/.config/sh/darwinrc"
  ;;
  Linux)
    [ -f "${HOME}/.config/sh/linuxrc" ]  && . "${HOME}/.config/sh/linuxrc"
  ;;
esac

#-----------------------------------------------------------------------------

if which nvim >/dev/null; then
  export EDITOR="nvim"
  export MANPAGER="nvim +Man!"
fi

#-----------------------------------------------------------------------------

export BROWSER="firefox"
