#!/usr/bin/env bash

#-----------------------------------------------------------------------------

export PATH="${HOME}/.local/sbin:${HOME}/.local/bin:${PATH}"

#-----------------------------------------------------------------------------

export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

#-----------------------------------------------------------------------------

case "$(uname)" in
  Darwin)
    test -f "${HOME}/.config/sh/darwinrc" && . "${_}"
  ;;
  Linux)
    test -f "${HOME}/.config/sh/linuxrc" && . "${_}"
  ;;
esac

#-----------------------------------------------------------------------------

if which nvim >/dev/null; then
  export EDITOR="nvim"
  export MANPAGER="nvim +Man!"
fi

#-----------------------------------------------------------------------------

export BROWSER="firefox"
