#!/usr/bin/env bash

#------------------------------------------------------------------------------

CURRENT_SHELL=$(ps -p $$ -oargs= | sed 's/.*[-/]//')

#------------------------------------------------------------------------------

 [ -z "$TMUX" ] && which tmux >/dev/null && tmux

# IMPORTS ---------------------------------------------------------------------

[ -f "$HOME/.env" ]     && . "$HOME/.env"     
[ -f "$HOME/.aliasrc" ] && . "$HOME/.aliasrc" 
[ -f "$HOME/.fzf.sh" ]  && . "$HOME/.fzf.sh"  

# SHELL-OPT VARIABLES ---------------------------------------------------------

export HISTCONTROL="ignoredups:erasedups"
export HISTFILE="$HOME/.cache/$CURRENT_SHELL/${CURRENT_SHELL}_history"
mkdir -p "${HISTFILE%/*}"

export LESSHISTFILE="/dev/null"

# PROMPT ----------------------------------------------------------------------

which starship >/dev/null && eval "$(starship init "${CURRENT_SHELL}")"

# MAN PAGE --------------------------------------------------------------------

if which nvim >/dev/null; then
  export MANPAGER="nvim +Man!"
else
  export LESS_TERMCAP_md=$'\e[1;32m'
fi
