source ~/.vim/rc/opts.vim
source ~/.vim/rc/keymaps.vim
source ~/.vim/rc/autocmds.vim
source ~/.vim/rc/plugins.vim

" ----------------------------------------------------------------------------

let s:colorschemes =<< trim END
  atom
  base16-flat
  base16-materia
  base16-material
  base16-onedark
  base16-solarflare
  focuspoint
  materialbox
  solarized8_high
END

execute 'colorscheme ' . s:colorschemes[rand() % (len(s:colorschemes) - 1)]
