#!/usr/bin/env zsh

#-----------------------------------------------------------------------------

[ -f $HOME/.shrc ] && . $HOME/.shrc

#-----------------------------------------------------------------------------

zsh_plugins=(
  hlissner/zsh-autopair
  # zdharma-continuum/fast-syntax-highlighting
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-syntax-highlighting
)

for plugin in $zsh_plugins; do
  plugin_dir=$HOME/.local/share/zsh/plugins/${plugin#*/}
  [ ! -d $plugin_dir ] && git clone https://github.com/$plugin $plugin_dir
  . $plugin_dir/zsh-*.plugin.zsh
done

#-----------------------------------------------------------------------------

zsh_completions=(
  zsh-users/zsh-completions
)

[ $(uname) = Darwin ] && zsh_completions+=(
  nilsonholger/osx-zsh-completions
)

for comp in $zsh_completions; do
  comp_dir=$HOME/.local/share/zsh/plugins/${comp#*/}
  [ ! -d $comp_dir ] && git clone -q https://github.com/$comp $comp_dir
  fpath=($fpath $(dirname $comp_dir/**/_*))
done

which brew &>/dev/null && fpath=($(brew --prefix)/share/zsh/site-functions $fpath)

fpath=($(echo "${FPATH//:/\n}" | awk '!x[$0]++')) # remove duplicate entries

zstyle ":completion::complete:*" cache-path $HOME/.cache/.zsh/zcompcache

autoload -Uz compinit && compinit -d $HOME/.cache/.zsh/zcompdump

#-----------------------------------------------------------------------------

setopt nobeep
setopt interactive_comments

setopt auto_cd
# setopt chase_links   # go to actual symlink dir rather in cd

# setopt null_glob
# setopt dot_glob
# setopt no_extended_glob
# setopt no_case_glob

setopt no_complete_in_word # completion evaluation includes chars past the cursor
setopt glob_complete # evaluate glob pattern for completion options
# setopt menu_complete # tab completion on first tab hit

setopt no_auto_remove_slash # dont remove trailing '/' produced from completion

setopt share_history hist_append inc_append_history
setopt extended_history

# setopt hist_verify
# setopt hist_no_store 
# setopt hist_ignore_space
# setopt hist_ignore_dups
# setopt hist_ignore_all_dups
# setopt hist_save_no_dups
# setopt hist_expire_dups_first
# setopt hist_find_no_dups

#-----------------------------------------------------------------------------

bindkey "^H" vi-cmd-mode

bindkey "^[[Z" .reverse-menu-complete #- Shift+Tab

bindkey "^[[A" up-line-or-search      #- Up arrow
bindkey "^[[B" down-line-or-search    #- Down arrow

bindkey "^K" up-line-or-search
bindkey "^J" down-line-or-search
