#!/usr/bin/env bash

# IMPORTS --------------------------------------------------------------------

[ -f "${HOME}/.shrc" ] && . "${HOME}/.shrc"

# SHELL-OPTS -----------------------------------------------------------------

shopt -u mailwarn
shopt -s checkwinsize

shopt -s dirspell # attempts to infer misspelled dir on `word-expansion`
shopt -s cdspell  # attempts to infer misspelled dir for `cd`

shopt -s hostcomplete

shopt -s dotglob
shopt -s nullglob
# shopt globskipdots
shopt -s nocaseglob
shopt -s nocasematch
shopt -s extglob

shopt -s histverify
shopt -s cmdhist
shopt -s histappend
# shopt lithist

if [ ${BASH_VERSINFO} -gt 3 ]; then
  shopt -s globstar # `**` performs recursive dir searches on filename expansion
  shopt -s autocd
  shopt -s progcomp_alias
fi

# READLINE -------------------------------------------------------------------

bind 'set mark-symlinked-directories on'
bind 'set colored-completion-prefix on'
bind 'set match-hidden-files on'

bind 'set visible-stats on'
bind 'set colored-stats on'

bind 'set history-preserve-point on'

# COMPLETION -----------------------------------------------------------------

bind 'set skip-completed-text on'
bind 'set show-all-if-ambiguous on'
bind 'set show-all-if-unmodified on'
bind 'set completion-ignore-case on'

# KEYBINDS -------------------------------------------------------------------

bind '"\C-k": history-substring-search-backward'
bind '"\C-j": history-substring-search-forward'

bind '"\t": menu-complete'            #\t => Tab
bind '"\e[Z": menu-complete-backward' #\t => Shift+Tab
